version: "3.9"
services:
  redis:
    hostname: redis
    image: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    hostname: mongodb
    restart: always
    ports:
      - "27017:27017"

  eureka-server:
    hostname: eureka-server
    image: shamprakash2000/eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    hostname: api-gateway
    image: shamprakash2000/api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - eureka-server
    environment:
      - "EUREKA_HOST=eureka-server"
      - "REDIS_HOST=redis"

  content-service:
    hostname: content-service
    image: shamprakash2000/content-service
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - eureka-server
      - api-gateway
    environment:
      - "MONGO_HOST=mongodb"
      - "EUREKA_HOST=eureka-server"
      - "USER_INTERACTION_HOST=user-interaction-service"

  user-service:
    hostname: user-service
    image: shamprakash2000/user-service
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
      - redis
      - eureka-server
      - api-gateway
    environment:
      - "MONGO_HOST=mongodb"
      - "EUREKA_HOST=eureka-server"
      - "REDIS_HOST=redis"

  user-interaction-service:
    hostname: user-interaction-service
    image: shamprakash2000/user-interaction-service
    ports:
      - "8083:8083"
    depends_on:
      - mongodb
      - eureka-server
      - api-gateway
    environment:
      - "MONGO_HOST=mongodb"
      - "EUREKA_HOST=eureka-server"