spring:
  application:
    name: API-GATEWAY

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      routes:
        ## service1
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/userService/**

        ## service2

        - id: CONTENT-SERVICE
          uri: lb://CONTENT-SERVICE
          predicates:
            - Path=/contentService/**
          filters:
            - AuthenticationFilter

        ## service3

        - id: USER-INTERACTION-SERVICE
          uri: lb://USER-INTERACTION-SERVICE
          predicates:
            - Path=/userInteractionService/**
          filters:
            - AuthenticationFilter



#        ## Service2
#        - id: service2
#          uri: lb://service2
#          predicates:
#            - Path=/service2/**
#          filters:
#            - StripPrefix=1
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: "http://${EUREKA_HOST:localhost}:8761/eureka"